Диплом, Этап 1
Siustoster/java-explore-with-me pull request #1
Opened 2024-09-05 14:32 UTC by Siustoster

2024-09-06 12:45 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2024-09-06 12:45 UTC, ErkinKasymaliev commented on stat/stat-client/src/main/java/ru/practicum/client/StatClientImpl.java
> +
лишняя строка, оставляйте только 1 одну пустую строку

2024-09-06 12:45 UTC, ErkinKasymaliev commented on stat/stat-server/src/main/java/ru/practicum/explorewme/statserver/controller/ServerController.java
> +            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
не надо этого, в параметрах сделайте так: @RequestParam @DateTimeFormatter("yyyy-MM-dd HH:mm:ss") LocalDateTime start, примерно так

2024-09-06 12:45 UTC, ErkinKasymaliev commented on stat/stat-server/src/main/java/ru/practicum/explorewme/statserver/exception/ErrorHandler.java
> +    public Map<String, String> handlePreValidationExceptions(MethodArgumentNotValidException exception) {
лучше вместо Map<String, String> создайте отдельный класс ErrorResponse

2024-09-06 18:22 UTC, Siustoster commented on stat/stat-client/src/main/java/ru/practicum/client/StatClientImpl.java
> +
Исправлено

2024-09-06 18:44 UTC, Siustoster commented on stat/stat-server/src/main/java/ru/practicum/explorewme/statserver/controller/ServerController.java
> +            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
Исправлено

2024-09-06 18:49 UTC, Siustoster commented on stat/stat-server/src/main/java/ru/practicum/explorewme/statserver/exception/ErrorHandler.java
> +    public Map<String, String> handlePreValidationExceptions(MethodArgumentNotValidException exception) {
Исправлено

2024-09-07 18:53 UTC, ErkinKasymaliev approved these changes
привет, работа принята!

2024-09-07 19:49 UTC, merged