Этап 2
Siustoster/java-explore-with-me pull request #2
Opened 2024-09-15 21:46 UTC by Siustoster

2024-09-16 14:10 UTC, ErkinKasymaliev requested changes
привет!
Общие замечания:
1) для инжекта используйте @RequiredArghContstuctor;
2) в некоторых классах нет модификаторов доступа
3) почему везде protected? что то я не нашел где вы наследуете
4) Не надо общих классов типа AdminController
5) Зачем вам AdminService, где вы смешали все сущности, у вас же есть CategoryService, EventService и так далее, используйте их

2024-09-16 14:10 UTC, ErkinKasymaliev commented on main-service/src/main/java/ru/practicum/mainservice/controller/AdminController.java
> +@AllArgsConstructor
для инжекта пожалуйста юзайте RequiredArgsConstructor

2024-09-16 14:10 UTC, ErkinKasymaliev commented on main-service/src/main/java/ru/practicum/mainservice/controller/AdminController.java
> +    @PostMapping("/categories")
вот этого не надо, для каждой сущности свой контроллер сделайте CategoryAdminController, EventAdminCOntroller...

2024-09-16 14:10 UTC, ErkinKasymaliev commented on main-service/src/main/java/ru/practicum/mainservice/controller/PrivateController.java
> +@AllArgsConstructor
смотрите комменты в AdminController

2024-09-16 14:10 UTC, ErkinKasymaliev commented on main-service/src/main/java/ru/practicum/mainservice/controller/PublicController.java
> +@AllArgsConstructor
смотрите комменты в AdminController

2024-09-16 14:10 UTC, ErkinKasymaliev commented on main-service/src/main/java/ru/practicum/mainservice/model/category/Category.java
> +    int id;
модификаторы доступа?

2024-09-16 14:10 UTC, ErkinKasymaliev commented on main-service/src/main/java/ru/practicum/mainservice/model/compilation/Compilation.java
> +    protected int id;
почему protected?

2024-09-16 14:10 UTC, ErkinKasymaliev commented on main-service/src/main/java/ru/practicum/mainservice/model/compilation/dto/CompilationDto.java
> +    protected Integer id;
дальше где наследуется?

2024-09-16 14:10 UTC, ErkinKasymaliev commented on main-service/src/main/java/ru/practicum/mainservice/model/event/Location.java
> +    int id;
модификаторы доступа

2024-09-16 14:10 UTC, ErkinKasymaliev commented on main-service/src/main/java/ru/practicum/mainservice/service/AdminService.java
> +public class AdminService {
разделить по сущностям

2024-09-16 14:10 UTC, ErkinKasymaliev commented on main-service/src/main/java/ru/practicum/mainservice/service/PrivateService.java
> +public class PrivateService {
разделить по сущностям

2024-09-16 14:10 UTC, ErkinKasymaliev commented on main-service/src/main/java/ru/practicum/mainservice/service/PublicService.java
> +public class PublicService {
разделить по сущностям

2024-09-16 17:38 UTC, Siustoster commented on main-service/src/main/java/ru/practicum/mainservice/controller/AdminController.java
> +@AllArgsConstructor
Исправлено

2024-09-16 17:38 UTC, Siustoster commented on main-service/src/main/java/ru/practicum/mainservice/controller/PrivateController.java
> +@AllArgsConstructor
Исправлено

2024-09-16 17:38 UTC, Siustoster commented on main-service/src/main/java/ru/practicum/mainservice/controller/PublicController.java
> +@AllArgsConstructor
Исправлено

2024-09-16 17:38 UTC, Siustoster commented on main-service/src/main/java/ru/practicum/mainservice/model/category/Category.java
> +    int id;
Исправлено

2024-09-16 17:38 UTC, Siustoster commented on main-service/src/main/java/ru/practicum/mainservice/model/compilation/Compilation.java
> +    protected int id;
Исправлено

2024-09-16 17:38 UTC, Siustoster commented on main-service/src/main/java/ru/practicum/mainservice/model/compilation/dto/CompilationDto.java
> +    protected Integer id;
Нигде, исправлено

2024-09-16 17:38 UTC, Siustoster commented on main-service/src/main/java/ru/practicum/mainservice/model/event/Location.java
> +    int id;
Исправлено

2024-09-17 17:47 UTC, Siustoster commented on main-service/src/main/java/ru/practicum/mainservice/controller/AdminController.java
> +    @PostMapping("/categories")
Исправлено

2024-09-17 17:47 UTC, Siustoster commented on main-service/src/main/java/ru/practicum/mainservice/service/AdminService.java
> +public class AdminService {
Исправлено

2024-09-17 17:47 UTC, Siustoster commented on main-service/src/main/java/ru/practicum/mainservice/service/PrivateService.java
> +public class PrivateService {
Исправлено

2024-09-17 17:47 UTC, Siustoster commented on main-service/src/main/java/ru/practicum/mainservice/service/PublicService.java
> +public class PublicService {
Исправлено

2024-09-18 05:11 UTC, ErkinKasymaliev approved these changes
привет, отлично!
работа принята

2024-09-18 08:59 UTC, merged